apiVersion: batch/v1
kind: Job
metadata:
  name: atong-marina-run-seed-0 
  labels:
    owner: atong
spec:
  template:
    spec:

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                    - NVIDIA-TITAN-RTX
                    - NVIDIA-A40
                    - NVIDIA-GeForce-RTX-3090
                    - NVIDIA-RTX-A6000
                    - NVIDIA-RTX-A5000
                    - NVIDIA-A10
                    - NVIDIA-GeForce-RTX-4090
      containers:
        - name: demo
          image: gitlab-registry.nrp-nautilus.io/a8tong/smart-moonshot/pixi-cuda:12.8
          command: ["/bin/bash"]
          args:
            - "-c"
            - >-
              set -euxo pipefail &&
              nvidia-smi -L &&
              cd /root/gurusmart/Moonshot &&
              pixi install --manifest-path pixi.toml &&
              unzip -q /root/gurusmart/MoonshotDatasetv3.zip -d /workspace/ &&
              cd /root/gurusmart/Moonshot &&
              pixi run --manifest-path pixi.toml -- torchrun --nproc_per_node=4 stage1.py --input_types {hsqc,c_nmr,h_nmr,mw,mass_spec} --seed 0 --experiment_name marina-run-seed-0 --num_workers 4 
              
          volumeMounts:
            - mountPath: "/root/gurusmart"
              name: atong-spectre
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /workspace
              name: data-unzip
          resources:
            limits:
              memory: 96Gi
              cpu: "16"
              ephemeral-storage: 600Gi
              nvidia.com/gpu: "4"
            requests:
              memory: 96Gi
              cpu: "16"
              ephemeral-storage: 600Gi
              nvidia.com/gpu: "4"

      volumes:
        - name: atong-spectre
          persistentVolumeClaim:
            claimName: atong-spectre
        - name: dshm
          emptyDir:
            medium: Memory
        - name: data-unzip
          emptyDir: {}
      restartPolicy: Never
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
  backoffLimit: 1
