apiVersion: batch/v1
kind: Job
metadata:
  name: atong-marina-reproduce-try-seed-0-seed-2 
  labels:
    owner: atong
spec:
  template:
    spec:

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  # - key: kubernetes.io/hostname
                  #   operator: NotIn
                  #   values:
                  #     - perfsonar.csusb.edu
                  #     - prp-gpu-3.t2.ucsd.edu
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                    - NVIDIA-TITAN-RTX
                    - NVIDIA-A40
                    - NVIDIA-GeForce-RTX-3090
                    - NVIDIA-RTX-A6000
                    - NVIDIA-RTX-A5000
                    - NVIDIA-A10
                    - NVIDIA-GeForce-RTX-4090
      containers:
        - name: demo
          image: gitlab-registry.nrp-nautilus.io/w6xu/guru-docker-image:3699f97c
          command: ["/bin/bash"]
          # /data/scripts/init.sh;
          args:
            - "-c"
            - >-
              nvidia-smi -L  &&
              cd /root/gurusmart  &&
              unzip -q /root/gurusmart/MoonshotDataset.zip -d /workspace/ &&
              cd /root/gurusmart/MARINAOld &&
              torchrun --nproc_per_node=4 stage1.py --input_types {hsqc,c_nmr,h_nmr,mw,mass_spec} --seed 0 --experiment_name marina-reproduce-try-seed-0-seed-2 --lambda_bce 0 --hybrid_loss 
          volumeMounts:
            # - mountPath: "/data"
            #   name: wangdong-smart-vol
            # - mountPath: "/root/autoencoder_denoiser/exps"
            #   name: wangdong-smart-vol
            - mountPath: "/root/gurusmart"
              name: atong-spectre
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /workspace
              name: data-unzip
          resources:
            limits:
              memory: 96Gi
              cpu: "16"
              ephemeral-storage: 600Gi
              nvidia.com/gpu: "4"
            requests:
              memory: 96Gi
              cpu: "16"
              ephemeral-storage: 600Gi
              nvidia.com/gpu: "4"

      volumes:
        # - name: wangdong-smart-vol
        #   persistentVolumeClaim:
        #     claimName: wangdong-smart-vol
        - name: atong-spectre
          persistentVolumeClaim:
            claimName: atong-spectre
        - name: dshm
          emptyDir:
            medium: Memory
        - name: data-unzip
          emptyDir: {}
      restartPolicy: Never
      # imagePullSecrets:
      #   - name: gitlab-auth
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
  backoffLimit: 1
