apiVersion: v1
kind: Pod
metadata:
  name: deepsat-docker-img
spec:


  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: nvidia.com/gpu.product
  #               operator: In
  #               values:
  #                 # - NVIDIA-GeForce-RTX-1080
  #                 # - NVIDIA-GeForce-RTX-1080-Ti
  #                 # - NVIDIA-GeForce-RTX-2080-Ti
  #                 - NVIDIA-TITAN-RTX
  #                 - NVIDIA-A40
  #                 - NVIDIA-GeForce-RTX-3090
  #                 - NVIDIA-RTX-A6000
  #                 - NVIDIA-RTX-A5000
  #                 - NVIDIA-RTX-A4000
  #                 - NVIDIA-A10
  #                 - NVIDIA-GeForce-RTX-4090

  
  containers:
    - name: pod-container
      image: xwd0418/deepsat-smart3-dash:from_ming
      command: ["sh"]
      args: 
      - "-c"
      - >- 
        sleep infinity 
      volumeMounts:
        # - mountPath: "/root"
        #   name: xwd-vscode
        - mountPath: "/root/gurusmart"
          name: smart-tess-code
        - mountPath: "/workspace"
          name: data-unzip
        - mountPath: /dev/shm
          name: dshm
        
      resources:
        limits:
          memory: 24Gi
          cpu: 8
          nvidia.com/gpu: 0
          ephemeral-storage: 200Gi
        requests:
          memory: 24Gi
          cpu: 8
          nvidia.com/gpu: 0
          ephemeral-storage: 200Gi
  
  volumes:
    - name: smart-tess-code
      persistentVolumeClaim:
        claimName: smart-tess-code
    # - name: xwd-vscode
    #   persistentVolumeClaim:
    #     claimName: xwd-vscode
    - name: dshm
      emptyDir:
        medium: Memory
    - name: data-unzip
      emptyDir: {}
